# Generated by Django 4.2.27 on 2026-04-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_backfill_temp_products_to_primary"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TempProduct",
        ),
    ]
