"""
Django settings for parcel_app project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a .env file using python-dotenv
load_dotenv(os.path.join(BASE_DIR, '.env'))


def _as_bool(value, default=False):
    if value is None:
        return default
    return str(value).strip().lower() in {'1', 'true', 'yes', 'on'}


def _as_list(value, default=None):
    if value is None:
        return list(default or [])

    return [item.strip() for item in str(value).split(',') if item.strip()]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _as_bool(os.getenv('DJANGO_DEBUG'), default=True)

DEFAULT_ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.42.70']
ALLOWED_HOSTS = _as_list(os.getenv('DJANGO_ALLOWED_HOSTS'), DEFAULT_ALLOWED_HOSTS)

# Application definition

INSTALLED_APPS = [
    'authentication.apps.AuthenticationConfig',
    'vendor.apps.VendorConfig',
    'courier.apps.CourierConfig',
    'banking.apps.BankingConfig',
    'complaints.apps.ComplaintsConfig',
    'geolocation.apps.GeolocationConfig',
    'email_service.apps.EmailServiceConfig',
    'messaging.apps.MessagingConfig',
    'core.apps.CoreConfig',
    'cart.apps.CartConfig',
    'dispatch.apps.DispatchConfig',
    'order.apps.OrderConfig',
    'product.apps.ProductConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_celery_results',
    'flower',
    'crispy_forms',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'authentication.drf_auth.SessionTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
}

# SESSION_EXPIRE_AT_BROWSER_CLOSE = True

CSRF_USE_SESSIONS = True

CSRF_COOKIE_HTTPONLY = True

DEFAULT_CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:3001',
    'http://127.0.0.1:3001',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:4173',
    'http://127.0.0.1:4173',
    'http://192.168.42.95:3000',
    'http://localhost:8080'
]
CORS_ALLOWED_ORIGINS = _as_list(os.getenv('DJANGO_CORS_ALLOWED_ORIGINS'), DEFAULT_CORS_ALLOWED_ORIGINS)

# Required for Django CSRF origin checks on cross-origin cookie-authenticated requests.
CSRF_TRUSTED_ORIGINS = _as_list(os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS'), CORS_ALLOWED_ORIGINS)

# Allow browser requests that send cookies/credentials from allowed origins.
CORS_ALLOW_CREDENTIALS = _as_bool(os.getenv('DJANGO_CORS_ALLOW_CREDENTIALS'), default=True)

# Allow custom session token header in CORS preflight requests
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-session-token',  # Custom header for admin session token
]


# Admin settings
DEFAULT_SUPER_ADMIN_EMAIL = os.environ.get('SUPER_ADMIN_EMAIL', 'admin@parcel.com')
DEFAULT_SUPER_ADMIN_PASSWORD = os.environ.get('SUPER_ADMIN_PASSWORD', '')  # Set via env

# Session settings
SESSION_COOKIE_AGE = 8 * 60 * 60  # 8 hours
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = _as_bool(os.getenv('DJANGO_SESSION_COOKIE_SECURE'), default=not DEBUG)
SESSION_COOKIE_SAMESITE = os.getenv('DJANGO_SESSION_COOKIE_SAMESITE', 'Lax' if DEBUG else 'None')
SESSION_COOKIE_DOMAIN = os.getenv('DJANGO_SESSION_COOKIE_DOMAIN') or None

CSRF_COOKIE_SECURE = _as_bool(os.getenv('DJANGO_CSRF_COOKIE_SECURE'), default=not DEBUG)
CSRF_COOKIE_SAMESITE = os.getenv('DJANGO_CSRF_COOKIE_SAMESITE', 'Lax' if DEBUG else 'None')
CSRF_COOKIE_DOMAIN = os.getenv('DJANGO_CSRF_COOKIE_DOMAIN') or None

AUTH_SESSION_COOKIE_SECURE = _as_bool(os.getenv('DJANGO_AUTH_SESSION_COOKIE_SECURE'), default=SESSION_COOKIE_SECURE)
AUTH_SESSION_COOKIE_SAMESITE = os.getenv('DJANGO_AUTH_SESSION_COOKIE_SAMESITE', SESSION_COOKIE_SAMESITE)
AUTH_SESSION_COOKIE_DOMAIN = os.getenv('DJANGO_AUTH_SESSION_COOKIE_DOMAIN') or SESSION_COOKIE_DOMAIN

AUTH_MARKER_COOKIE_SECURE = _as_bool(os.getenv('DJANGO_AUTH_MARKER_COOKIE_SECURE'), default=AUTH_SESSION_COOKIE_SECURE)
AUTH_MARKER_COOKIE_SAMESITE = os.getenv('DJANGO_AUTH_MARKER_COOKIE_SAMESITE', AUTH_SESSION_COOKIE_SAMESITE)
AUTH_MARKER_COOKIE_DOMAIN = os.getenv('DJANGO_AUTH_MARKER_COOKIE_DOMAIN') or AUTH_SESSION_COOKIE_DOMAIN

# python manage.py create_super_admin --email=admin@yourdomain.com --password=StrongPassword123

ROOT_URLCONF = 'parcel_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

WSGI_APPLICATION = 'parcel_app.wsgi.application'


CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DATABASE_NAME', 'parcel_db'),
        'USER': os.getenv('DATABASE_USER', 'postgres'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD', ''),
        'HOST': os.getenv('DATABASE_HOST', '127.0.0.1'),
        'PORT': os.getenv('DATABASE_PORT', '5432'),
    }
}

# If a full DATABASE_URL is provided (e.g. from Heroku), override the above.
if os.getenv('DATABASE_URL'):
    try:
        import dj_database_url
        DATABASES['default'] = dj_database_url.parse(os.getenv('DATABASE_URL'), conn_max_age=600)
    except Exception:
        # dj-database-url not installed yet; keep the env-var-based config
        pass

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

USE_S3 = _as_bool(os.getenv('USE_S3'), default=False)

if USE_S3:
    # Backward-compatible default: infer public/private mode from AWS_QUERYSTRING_AUTH
    # when S3_MEDIA_PUBLIC is not explicitly provided.
    _legacy_qs_auth_default = _as_bool(os.getenv('AWS_QUERYSTRING_AUTH'), default=False)
    S3_MEDIA_PUBLIC = _as_bool(os.getenv('S3_MEDIA_PUBLIC'), default=(not _legacy_qs_auth_default))

    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', '')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', '')
    AWS_S3_SIGNATURE_VERSION = os.getenv('AWS_S3_SIGNATURE_VERSION') or 's3v4'
    AWS_S3_FILE_OVERWRITE = _as_bool(os.getenv('AWS_S3_FILE_OVERWRITE'), default=False)

    # None string should map to Python None for django-storages defaults.
    _aws_default_acl = os.getenv('AWS_DEFAULT_ACL')
    AWS_DEFAULT_ACL = None if not _aws_default_acl or _aws_default_acl.lower() == 'none' else _aws_default_acl

    AWS_QUERYSTRING_AUTH = _as_bool(os.getenv('AWS_QUERYSTRING_AUTH'), default=(not S3_MEDIA_PUBLIC))
    if not S3_MEDIA_PUBLIC and not AWS_QUERYSTRING_AUTH:
        raise ValueError('S3_MEDIA_PUBLIC=False requires AWS_QUERYSTRING_AUTH=True.')

    AWS_S3_ENCRYPTION = os.getenv('AWS_S3_ENCRYPTION', 'AES256').strip()
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': os.getenv('AWS_S3_CACHE_CONTROL', 'max-age=86400'),
    }
    if AWS_S3_ENCRYPTION and AWS_S3_ENCRYPTION.lower() != 'none':
        AWS_S3_OBJECT_PARAMETERS['ServerSideEncryption'] = AWS_S3_ENCRYPTION

    AWS_S3_ADDRESSING_STYLE = os.getenv('AWS_S3_ADDRESSING_STYLE', 'virtual')
    AWS_S3_URL_PROTOCOL = os.getenv('AWS_S3_URL_PROTOCOL', 'https:')
    AWS_S3_VERIFY = _as_bool(os.getenv('AWS_S3_VERIFY'), default=True)

    AWS_LOCATION = os.getenv('AWS_LOCATION', 'media')
    AWS_S3_CUSTOM_DOMAIN = os.getenv('AWS_S3_CUSTOM_DOMAIN')
    AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL') or None

    if not AWS_STORAGE_BUCKET_NAME:
        raise ValueError('USE_S3=True but AWS_STORAGE_BUCKET_NAME is not set.')

    if not AWS_S3_CUSTOM_DOMAIN:
        if AWS_S3_REGION_NAME:
            AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"
        else:
            AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"

    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

    MEDIA_URL = f"{AWS_S3_URL_PROTOCOL}//{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/"
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

GEOIP_PATH = os.path.join(BASE_DIR, 'geoip')

EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'parcel_backends/messages')

RECIPIENT_ADDRESS = os.getenv('RECIPIENT_ADDRESS')

# Shared token for trusted internal payment status sync calls.
PAYMENT_SYNC_TOKEN = os.getenv('PAYMENT_SYNC_TOKEN', '')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
