# Generated by Django 4.2.27 on 2026-03-31 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Assignment"),
                            ("assigned", "Assigned to Courier"),
                            ("picking_up", "Picking Up from Vendors"),
                            ("in_transit", "In Transit to Customer"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("delayed", "Delayed"),
                            ("returned", "Returned to Vendor"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("estimated_pickup_time", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_delivery_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("pickup_addresses", models.JSONField(default=list)),
                ("delivery_address", models.JSONField(default=dict)),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "estimated_duration_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                ("courier_notes", models.TextField(blank=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "courier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatches",
                        to="authentication.courieruser",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch",
                        to="order.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispatch",
                "verbose_name_plural": "Dispatches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DispatchRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("waypoints", models.JSONField(default=list)),
                ("optimized_route", models.JSONField(blank=True, default=dict)),
                (
                    "total_distance_km",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("estimated_duration_minutes", models.IntegerField()),
                (
                    "fuel_estimate_liters",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("traffic_conditions", models.CharField(blank=True, max_length=50)),
                ("traffic_delay_minutes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dispatch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route",
                        to="dispatch.dispatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispatch Route",
                "verbose_name_plural": "Dispatch Routes",
            },
        ),
        migrations.CreateModel(
            name="CourierLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "speed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "bearing",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "altitude",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="authentication.courieruser",
                    ),
                ),
                (
                    "dispatch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="dispatch.dispatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Courier Location",
                "verbose_name_plural": "Courier Locations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DispatchStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("location", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_status_changes",
                        to="authentication.adminuser",
                    ),
                ),
                (
                    "dispatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="dispatch.dispatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispatch Status History",
                "verbose_name_plural": "Dispatch Status Histories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["dispatch", "created_at"],
                        name="dispatch_di_dispatc_99b368_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DispatchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Pickup"),
                            ("picked_up", "Picked Up from Vendor"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered to Customer"),
                            ("cancelled", "Cancelled"),
                            ("returned", "Returned to Vendor"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_ready_for_pickup", models.BooleanField(default=False)),
                ("is_picked_up", models.BooleanField(default=False)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pickup_confirmation_code",
                    models.CharField(blank=True, max_length=10),
                ),
                ("is_delivered", models.BooleanField(default=False)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_confirmation_code",
                    models.CharField(blank=True, max_length=10),
                ),
                ("customer_signature", models.TextField(blank=True)),
                ("vendor_notes", models.TextField(blank=True)),
                ("courier_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dispatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="dispatch.dispatch",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_items",
                        to="order.orderitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispatch Item",
                "verbose_name_plural": "Dispatch Items",
                "indexes": [
                    models.Index(
                        fields=["dispatch", "status"],
                        name="dispatch_di_dispatc_9f63a6_idx",
                    ),
                    models.Index(
                        fields=["order_item", "status"],
                        name="dispatch_di_order_i_91bb26_idx",
                    ),
                ],
                "unique_together": {("dispatch", "order_item")},
            },
        ),
        migrations.AddIndex(
            model_name="dispatch",
            index=models.Index(
                fields=["tracking_number"], name="dispatch_di_trackin_da5ba9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatch",
            index=models.Index(
                fields=["order", "status"], name="dispatch_di_order_i_0b52aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatch",
            index=models.Index(
                fields=["courier", "status"], name="dispatch_di_courier_511c60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatch",
            index=models.Index(
                fields=["status", "estimated_delivery_time"],
                name="dispatch_di_status_489439_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="courierlocation",
            index=models.Index(
                fields=["courier", "created_at"], name="dispatch_co_courier_842e43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courierlocation",
            index=models.Index(
                fields=["dispatch", "created_at"], name="dispatch_co_dispatc_f4519d_idx"
            ),
        ),
    ]
