# Generated by Django 4.2.27 on 2026-04-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerComplaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_email", models.CharField(max_length=70)),
                ("complaint_subject", models.CharField(max_length=125)),
                (
                    "courier_involved",
                    models.CharField(default="Anonymous", max_length=125),
                ),
                ("complaint_detail", models.TextField(max_length=1000)),
                ("is_resolved", models.BooleanField()),
                ("is_satisfied", models.BooleanField()),
                ("created_at", models.CharField(default="dummy_date", max_length=50)),
                ("updated_at", models.CharField(default="dummy_date", max_length=50)),
            ],
        ),
    ]
