# Generated by Django 4.2.27 on 2026-03-31 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=80, unique=True)),
                ("password", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone", models.CharField(blank=True, max_length=14, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Administrator"),
                            ("admin", "Administrator"),
                            ("staff", "Staff Member"),
                            ("operator", "System Operator"),
                        ],
                        default="staff",
                        max_length=20,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="staff-photo/"),
                ),
            ],
            options={
                "verbose_name": "Admin User",
                "verbose_name_plural": "Admin Users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=80, unique=True)),
                ("password", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone", models.CharField(blank=True, max_length=14, null=True)),
                ("country", models.CharField(blank=True, max_length=50)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("street", models.CharField(blank=True, max_length=50)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("premium_customer", "Premium Customer"),
                            ("anonymous", "Anonymous Customer"),
                        ],
                        default="customer",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer User",
                "verbose_name_plural": "Customer Users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=80, unique=True)),
                ("password", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=14)),
                ("business_name", models.CharField(blank=True, max_length=100)),
                ("business_country", models.CharField(blank=True, max_length=50)),
                ("business_state", models.CharField(blank=True, max_length=50)),
                ("business_street", models.CharField(blank=True, max_length=50)),
                ("business_category", models.CharField(blank=True, max_length=50)),
                ("cac_reg_no", models.CharField(blank=True, max_length=20)),
                ("nin", models.CharField(blank=True, max_length=11)),
                (
                    "role",
                    models.CharField(
                        choices=[("vendor", "Vendor")], default="vendor", max_length=20
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_vendors",
                        to="authentication.adminuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TempVendorUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=80, unique=True)),
                ("password", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=14)),
                ("business_name", models.CharField(blank=True, max_length=100)),
                ("business_country", models.CharField(blank=True, max_length=50)),
                ("business_state", models.CharField(blank=True, max_length=50)),
                ("business_street", models.CharField(blank=True, max_length=50)),
                ("business_category", models.CharField(blank=True, max_length=50)),
                ("cac_reg_no", models.CharField(blank=True, max_length=20)),
                ("nin", models.CharField(blank=True, max_length=11)),
                (
                    "role",
                    models.CharField(
                        choices=[("vendor", "Vendor")], default="vendor", max_length=20
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_temp_vendors",
                        to="authentication.adminuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TempCourierUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=80, unique=True)),
                ("password", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=14)),
                ("business_country", models.CharField(blank=True, max_length=50)),
                ("business_state", models.CharField(blank=True, max_length=50)),
                ("business_street", models.CharField(blank=True, max_length=50)),
                ("cac_reg_no", models.CharField(blank=True, max_length=20)),
                ("nin", models.CharField(blank=True, max_length=11)),
                (
                    "role",
                    models.CharField(
                        choices=[("courier", "Courier")],
                        default="courier",
                        max_length=20,
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("vehicle_type", models.CharField(blank=True, max_length=50)),
                ("vehicle_registration", models.CharField(blank=True, max_length=20)),
                ("service_area", models.CharField(blank=True, max_length=100)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_temp_couriers",
                        to="authentication.adminuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CourierUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=80, unique=True)),
                ("password", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=14)),
                ("business_country", models.CharField(blank=True, max_length=50)),
                ("business_state", models.CharField(blank=True, max_length=50)),
                ("business_street", models.CharField(blank=True, max_length=50)),
                ("cac_reg_no", models.CharField(blank=True, max_length=20)),
                ("nin", models.CharField(blank=True, max_length=11)),
                (
                    "role",
                    models.CharField(
                        choices=[("courier", "Courier")],
                        default="courier",
                        max_length=20,
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("vehicle_type", models.CharField(blank=True, max_length=50)),
                ("vehicle_registration", models.CharField(blank=True, max_length=20)),
                ("service_area", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_delivery", "On Delivery"),
                            ("offline", "Offline"),
                            ("suspended", "Suspended"),
                            ("inactive", "Inactive"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                (
                    "current_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "current_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("last_location_update", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_couriers",
                        to="authentication.adminuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("session_token", models.CharField(max_length=255, unique=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_token"], name="authenticat_session_30c7e0_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id", "is_active"],
                        name="authenticat_content_6edd98_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("token", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset Token",
                "verbose_name_plural": "Password Reset Tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="authenticat_token_3288c7_idx"),
                    models.Index(
                        fields=["content_type", "object_id", "is_used"],
                        name="authenticat_content_0bd166_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("create", "Create Record"),
                            ("update", "Update Record"),
                            ("delete", "Delete Record"),
                            ("password_change", "Password Change"),
                            ("permission_change", "Permission Change"),
                        ],
                        max_length=50,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("object_id_ref", models.CharField(blank=True, max_length=100)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "action"],
                        name="authenticat_content_807be6_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="authenticat_created_d9c5cc_idx"
                    ),
                ],
            },
        ),
    ]
