# Generated by Django 4.2.27 on 2026-04-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_backfill_temp_users_to_primary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tempvendoruser",
            name="approved_by",
        ),
        migrations.DeleteModel(
            name="TempCourierUser",
        ),
        migrations.DeleteModel(
            name="TempVendorUser",
        ),
    ]
