# Generated by Django 4.2.27 on 2026-04-16 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0005_remove_tempvendoruser_approved_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("total_items", models.IntegerField(default=0)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "shipping_method",
                    models.CharField(
                        choices=[("pick_up", "Pick Up"), ("delivery", "Delivery")],
                        default="pick_up",
                        max_length=25,
                    ),
                ),
                ("zip_code", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to="authentication.customeruser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Session",
                "verbose_name_plural": "Cart Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CartDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField()),
                ("product_name", models.CharField(max_length=100)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.cartsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Detail",
                "verbose_name_plural": "Cart Details",
                "ordering": ["created_at"],
                "unique_together": {("session", "product_id")},
            },
        ),
    ]
