# Generated by Django 4.2.27 on 2026-04-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourierBankDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=70)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("Savings", "Savings"), ("Current", "Current")],
                        max_length=20,
                    ),
                ),
                ("account_name", models.CharField(max_length=70)),
                ("courier_email", models.EmailField(max_length=70)),
                ("account_no", models.CharField(max_length=15)),
                ("added_at", models.CharField(max_length=50)),
                ("updated_at", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="VendorBankDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=70)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("Savings", "Savings"), ("Current", "Current")],
                        max_length=20,
                    ),
                ),
                ("account_name", models.CharField(max_length=70)),
                ("vendor_email", models.EmailField(max_length=70)),
                ("account_no", models.CharField(max_length=15)),
                ("added_at", models.CharField(max_length=50)),
                ("updated_at", models.CharField(max_length=50)),
            ],
        ),
    ]
